version: 2.1

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.8.5"
    steps:
      - checkout
      - run: python3 main.py
  

workflows:
  build:
    jobs:
      - build