# CircleCI configuration file
version: 2.1

jobs:
  build:
  working_directory: ~/circleci-python
    docker:
     - image: cimg/base:2022.05
    steps:
      - checkout
      -run: python3 main.py

workflows:
    #Store manager
    store_manager:
      jobs:
        - build
      on:
        branches:
          - master



