version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps: 
      - checkout

      - run:
          name: "Installing dependancies"
          command: pip install requirements.txt

      - run: python3 main.py
    


  say_goodbye:
    docker:
     - image: cimg/base:2022.05
    steps:
      - run: echo "Say goodbye to YAML!"

workflows:
  # Name of workflow
  build:

    # List of jobs that will run
    jobs:
      - build
      - say_goodbye