
# CircleCI configuration file
version: 2.1

jobs:
  # Job one with a unique name
  build:
    docker:
     - image: "circleci/python:3.6.4"
    steps:
      - run: 
          -checkout
          -run: python3 main.py         
  # Job two with a unique name
  say_goodbye:
    docker:
     - image: cimg/base:2022.05
    steps:
      - run: echo "Say goodbye to YAML!"

workflows:
  # Name of workflow
  build:

    # List of jobs that will run
    jobs:
      - build
      - say_goodbye